version: '3.9'
services:
  meloman_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: meloman_db
      MYSQL_USER: yeldos
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  meloman_app:
    build: .
    ports:
      - "5050:5000"
    depends_on:
      - meloman_db
    environment:
      FLASK_ENV: "development"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  meloman_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: meloman_db
      PMA_USER: yeldos
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8888:80"
    depends_on:
      - meloman_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mysql_data:
    driver: local
